seed: 1234
torch_home: '/home/u9775528/.local/lib/python3.7/site-packages/torch/'
froze: False

dataset:
  name: 'CelebDF'
  pair: False
  ffpp:
    data_root: '/work/u9775528/'
    data_types: [ 'jpeg_10_images' ]
    compressions: 'c23'
    num_frames: 50
    methods: 
    has_mask: False
    mask_size: 10
    pair: True
  CelebDF: 
    data_root: '/work/u9775528/CelebDF'
    data_types: 'jpeg'
    num_frames: 50
    sample: 0
  DFD: 
    data_root: '/work/u9775528/DFD'
    data_types: ''
    num_frames: 25

  wild_deepfake:
    root: 'PATH TO YOUR DATA ROOT'




test:
  batch_size: 32
  threshold: 0.5
  record_results: True
  


train:
  batch_size: 32
  threshold: 0.5
  record_results: True
